### ISSUE TITLE
item 2 in _argtypes_ passes a union by value, which is unsupported.

### ISSUE THREAD

**Issue by mengxin239** [lesssafe/rdp_shell#1]
```Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 123, in WINFUNCTYPE
    return _win_functype_cache[(restype, argtypes, flags)]
KeyError: (<class 'ctypes.HRESULT'>, (<class 'ctypes.c_long'>, <class 'comtypes.automation.tagVARIANT'>, <class 'ctypes.c_long'>, <class 'comtypes.LP_POINTER(IUIAutomationTextRange)'>), 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Rdp_Pluse_Action_powershell.py", line 1, in <module>
    from pywinauto.application import Application
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\__init__.py", line 40, in <module>
    from . import findwindows
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\findwindows.py", line 42, in <module>
    from . import controls
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\controls\__init__.py", line 36, in <module>
    from . import uiawrapper # register "uia" back-end (at the end of uiawrapper module)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\controls\uiawrapper.py", line 44, in <module>
    from ..uia_defines import IUIA
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\uia_defines.py", line 175, in <module>
    pattern_ids = _build_pattern_ids_dic()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\uia_defines.py", line 163, in _build_pattern_ids_dic
    if hasattr(IUIA().ui_automation_client, cls_name):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\uia_defines.py", line 50, in __call__
    cls._instances[cls] = super(_Singleton, cls).__call__(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\uia_defines.py", line 60, in __init__
    self.UIA_dll = comtypes.client.GetModule('UIAutomationCore.dll')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\comtypes\client\_generate.py", line 159, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\comtypes\client\_generate.py", line 242, in _CreateWrapper
    mod = _my_import(fullname)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\comtypes\client\_generate.py", line 26, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\comtypes\gen\_944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0.py", line 717, in <module>
    IUIAutomationTextRange._methods_ = [
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\comtypes\__init__.py", line 328, in __setattr__
    self._make_methods(value)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\comtypes\__init__.py", line 697, in _make_methods
    prototype = WINFUNCTYPE(restype, *argtypes)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 125, in WINFUNCTYPE
    class WinFunctionType(_CFuncPtr):
TypeError: item 2 in _argtypes_ passes a union by value, which is unsupported.
```
我用python3.8的时候他抛出了这么一个错误，我用python3.10的时候就可以正常运行
但是我的机器是windows2008，有什么办法解决吗

**Comment by lesssafe** [comment]
有些版本的python确实不支持这个库，可以试着用下面方法解决
解决办法:升级3.8.2+或者降低python版本 3.7.4-
